### ISSUE TITLE
Update to Python 3 and PyQt5

### ISSUE THREAD

**Issue by raacampbell** [raacampbell/lasagna#176]
Lack of PyQt5 support in Lasagna is making running it on a Mac even more annoying than it was before, since Qt4 is increasingly hard to install on later versions of OX X. However, PyQtGraph seems to be moving to PyQt5 so it may be safe to upgrade now. This needs to be done carefully in case stuff breaks. 

- [x] Move to Python 3 and confirm that everything continues to work
- [x] Then try PyQt5

**Comment by raacampbell** [comment]
The bulk of the Python 3 conversion is done: 9311c75770f6bae0b7e61659bc485997d4655300

**Comment by raacampbell** [comment]
PyQt5 conversion done: 80276eff492f139e5a0e6f8b5d93f18db37ddc98

**Comment by ablot** [comment]
Seems to work for me.
